### ISSUE TITLE
请问有遇到这个问题的吗 该怎么解决呢？

### ISSUE THREAD

**Issue by littleloverlalala** [we0091234/Chinese_license_plate_detection_recognition#15]
Traceback (most recent call last):
  File "D:\huohu\Chinese_license_plate_detection_recognition-main\Chinese_license_plate_detection_recognition-main\train.py", line 520, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "D:\huohu\Chinese_license_plate_detection_recognition-main\Chinese_license_plate_detection_recognition-main\train.py", line 187, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "D:\huohu\Chinese_license_plate_detection_recognition-main\Chinese_license_plate_detection_recognition-main\utils\face_datasets.py", line 62, in create_dataloader
    dataset = LoadFaceImagesAndLabels(path, imgsz, batch_size,
  File "D:\huohu\Chinese_license_plate_detection_recognition-main\Chinese_license_plate_detection_recognition-main\utils\face_datasets.py", line 164, in __init__
    labels, shapes = zip(*cache.values())
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by we0091234** [comment]
> Traceback (most recent call last): File "D:\huohu\Chinese_license_plate_detection_recognition-main\Chinese_license_plate_detection_recognition-main\train.py", line 520, in train(hyp, opt, device, tb_writer, wandb) File "D:\huohu\Chinese_license_plate_detection_recognition-main\Chinese_license_plate_detection_recognition-main\train.py", line 187, in train dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt, File "D:\huohu\Chinese_license_plate_detection_recognition-main\Chinese_license_plate_detection_recognition-main\utils\face_datasets.py", line 62, in create_dataloader dataset = LoadFaceImagesAndLabels(path, imgsz, batch_size, File "D:\huohu\Chinese_license_plate_detection_recognition-main\Chinese_license_plate_detection_recognition-main\utils\face_datasets.py", line 164, in **init** labels, shapes = zip(*cache.values()) ValueError: not enough values to unpack (expected 2, got 0)

没有啊，你加群问问吧，看看群友有没有遇到过
