### ISSUE TITLE
格式转换，另加一个报错

### ISSUE THREAD

**Issue by yyqAlisa** [we0091234/Chinese_license_plate_detection_recognition#20]
label x y w h  pt1x pt1y pt2x pt2y pt3x pt3y pt4x pt4y

原本的数据是labelme标注的，是图片和标签，图片是jpg格式，标签是json结尾的格式。我自己转换成了 yolov5的格式，例子如下
0 0.4583984374999998 0.14062499999999992 0.39101562499999987 0.15069444444444435。
请问你们的格式是怎么转换的
另外还有个bug，

Scanning '/app/dataset/fourth_project/plate_number/plate_dataset_1/labels/train' for images and labels... 1305 found, 0 missing, 0 empty, 1305 corrupted: 100%|██████████| 1305/1305 [00:39<00:00, 32.67it/s]
New cache created: /app/dataset/fourth_project/plate_number/plate_dataset_1/labels/train.cache
Scanning '/app/dataset/fourth_project/plate_number/plate_dataset_1/labels/train.cache' for images and labels... 1305 found, 0 missing, 0 empty, 1305 corrupted: 100%|██████████| 1305/1305 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/anaconda3/envs/py_37/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/app/plate_number/Chinese_license_plate_detection_recognition-main/utils/torch_utils.py", line 32, in torch_distributed_zero_first
    yield
  File "/app/plate_number/Chinese_license_plate_detection_recognition-main/utils/face_datasets.py", line 72, in create_dataloader
    image_weights=image_weights,
  File "/app/plate_number/Chinese_license_plate_detection_recognition-main/utils/face_datasets.py", line 166, in __init__
    labels, shapes = zip(*cache.values())
ValueError: not enough values to unpack (expected 2, got 0)

这cache的值是什么

**Comment by dangzheng0430** [comment]
同问，我也遇到这个问题，您解决了吗？
